# config.mk is generated by configure
CTDLDIR := /root/citadel/citadel
CFLAGS := -ggdb -DHAVE_OPENSSL -DBUILD_ID=\"v957-38-g71c3e52b0\" -DCTDLDIR=\"/root/citadel/citadel\"
LDFLAGS :=  -lssl -lcrypto -lz
