# config.mk is generated by configure
CTDLDIR := /root/citadel/citadel
CFLAGS := -ggdb -DHAVE_OPENSSL -DBUILD_ID=\"v972-1-gc13dec1e4\" -DCTDLDIR=\"/root/citadel/citadel\"
LDFLAGS :=  -lssl -lcrypto -lz
