# config.mk is generated by configure
CTDLDIR := /root/citadel/citadel
CFLAGS := -ggdb -DHAVE_OPENSSL -DBUILD_ID=\"v957-74-g825c7f252\" -DCTDLDIR=\"/root/citadel/citadel\"
LDFLAGS :=  -lssl -lcrypto -lz
